language: node_js
sudo: required
dist: trusty
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
node_js: 8
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local --plugin
  sauce; fi
env:
  global:
  - secure: fw+bOfTcdoy4r8bTrZqJIrA9yTF6k8BmrTA96dr/OqNbfsSwumiXE1Ht9RwZjmVs7O/LaQxmgj4TpYDZPXVO4PCMaGyNE/hBUSnBx4y4GXQLvH10DHKa2RAy6DAcefL/dKxpZilwcaNVOxX4K2OWxyWscpMAkToOfpqhHW2gROJdX3A93zpKTP80OSHIIvRIZyNJ7F69vo2/BPF+trm6Y4EoASTuJh4Mj0Y4KpXesTmCrBNEVN3GhK3S4YPx+UUgjZMBz5zaxBsi4RxkJ1AEdRTGb78AqoKdVLlUq3/Ch4Y8DKYZSGKLDFumqDn7FV3118haldq7m5WitDqqkfVrA3e/ZnyC3iFchvrjdshXvpxWiVb/FN5oq0JLxBgoAM+Qa/3mChrBKfxEtMpNiMJZYidiyggpUX50AAW7YjQeF5/vYEqvHuMjeRPJ9709P7BDEUpJ2b4R4yh8rbv4+4MXeJwK2kqPkoDvf+/OVbcZePhqfO8KRre59iSDHV8MMAtTmro2DM43toWU1ZhWWO2z5DF/G4KzPXJn4F6UZbzEXrbjHzICZ2CGRqNsdWeb3UKYNk96LaJiNsCxVYH0krfXmpSNZGwAVlFq8a0965wYEO4u38XiLaqXZLDAUHtKZsw+0W1J3bt6DqmxrMnLF4akmPGXVpyDGSAC6IiuvXP59EA=
  - secure: S4lzXpEHNUawGlf3aICX+7gP6/MlNSNVoNzbLZ3XPNO6Sx1YoGRJdTiDUhnc8IcfWBwy9nV08/zugbyJYumoYI0vMK52cQCYBbeOZ9rcB8M0fjiiaiLVnV9vfQWm569I6BlYvR6NXJzjtuTGZLkA/QAhV9Kg+0Kpm1NiqJHCOzAgMnim4kQDKcI5W9uKZkzcj1ZTXa5UP6HwTvi9avio9NK0yve8DD+obVtyhETMDBvtCuIQsOnlQb4kHYqgXlCHK4dgKOu7YzuYNpl47vdsG8Eqb0bfVcNgjBPb5WcVndGZzozWZ19AQ17Ce7eS3Mf1bAFpCdvPTNmQJyGHVam7cu+INzhneww7E0JJrVM1OPbMuRlrjEgEmORTmFu3JzR3eiwNIxjF4yXoXd1ORDFmKwhk1SXmKnghE/msfeTvpQ8WEiteTm0b3XqNuQLoVKMDjbv74U2RkAKsq2o0XSn/UcmKFkmRF/oS/j4bvcuIZ0wn7+yBaUhugMhQJyzB12K+NspA+D2Uje1y7MYWpKD27q9fh/XiYbIKZF3NvHrRGkIRoiIFcKeWrXtO323tQUXZDXyq7rEU72dpyGCcJKzhkYfbiXckJmSyU6fMmx1X9j5ff/xnInImbCzP79nf+3kYjoOFU63yZYkXAGjJaEW5wblEnp8PmkzYzLP7MOzITTI=
